//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorselHW1_IsmailTunaSeydisehirli
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDBEntities : DbContext
    {
        public SDBEntities()
            : base("name=SDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LessonDB> LessonDBs { get; set; }
        public virtual DbSet<StaffDB> StaffDBs { get; set; }
        public virtual DbSet<StudentDB> StudentDBs { get; set; }
        public virtual DbSet<StudentLessonDB> StudentLessonDBs { get; set; }
    }
}
