//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorselHW1_IsmailTunaSeydisehirli
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StaffDB()
        {
            this.LessonDBs = new HashSet<LessonDB>();
        }
    
        public string Staff_ID { get; set; }
        public string Staff_Name { get; set; }
        public string Staff_Duty { get; set; }
        public string Staff_Division { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonDB> LessonDBs { get; set; }
    }
}
