//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorselHW1_IsmailTunaSeydisehirli
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentDB()
        {
            this.StudentLessonDBs = new HashSet<StudentLessonDB>();
        }
    
        public string Student_ID { get; set; }
        public string Student_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public int Student_No { get; set; }
        public System.DateTime Date_of_Register { get; set; }
        public string Major { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLessonDB> StudentLessonDBs { get; set; }
    }
}
