//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GorselHW1_IsmailTunaSeydisehirli
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLessonDB
    {
        public string Student_and_Lesson_ID { get; set; }
        public string Student_taking_the_Lesson { get; set; }
        public string Lesson_Taken { get; set; }
    
        public virtual LessonDB LessonDB { get; set; }
        public virtual StudentDB StudentDB { get; set; }
    }
}
